"""agrega tabla dq_rejections

Revision ID: 191477b96f61
Revises: 62bdff1224fe
Create Date: 2026-02-06 18:19:59.335161

"""
from alembic import op
import sqlalchemy as sa

revision = "191477b96f61"
down_revision = '62bdff1224fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
