"""agrega tabla dq_rejections

Revision ID: 62bdff1224fe
Revises: 83bd32e2611d
Create Date: 2026-02-06 18:17:23.722894

"""
from alembic import op
import sqlalchemy as sa

revision = "62bdff1224fe"
down_revision = '83bd32e2611d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
