"""crea tablas base (departments, jobs, hired_employees)

Revision ID: 65ce115e0f7f
Revises: 
Create Date: 2026-02-06 17:28:32.039152

"""
from alembic import op
import sqlalchemy as sa

revision = "65ce115e0f7f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hired_employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_hired_datetime', 'hired_employees', ['datetime'], unique=False)
    op.create_index('idx_hired_dept_job_datetime', 'hired_employees', ['department_id', 'job_id', 'datetime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_hired_dept_job_datetime', table_name='hired_employees')
    op.drop_index('idx_hired_datetime', table_name='hired_employees')
    op.drop_table('hired_employees')
    op.drop_table('jobs')
    op.drop_table('departments')
    # ### end Alembic commands ###
