"""agrega tabla dq_rejections

Revision ID: 83bd32e2611d
Revises: 65ce115e0f7f
Create Date: 2026-02-06 18:15:10.246691

"""
from alembic import op
import sqlalchemy as sa

revision = "83bd32e2611d"
down_revision = '65ce115e0f7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
